// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfhHr9cEoqQvLeQr9GTCEThr-79cGlKEU',
    appId: '1:584143822337:web:706a9d33662ac1dc50ea00',
    messagingSenderId: '584143822337',
    projectId: 'mychatapp-e72a0',
    authDomain: 'mychatapp-e72a0.firebaseapp.com',
    storageBucket: 'mychatapp-e72a0.firebasestorage.app',
    measurementId: 'G-GMLKVKXP2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSwS-_cq6j4BIN8S35NiaOkdG_P4DCE8',
    appId: '1:584143822337:android:a2b6529a38d9245b50ea00',
    messagingSenderId: '584143822337',
    projectId: 'mychatapp-e72a0',
    storageBucket: 'mychatapp-e72a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo9pe7VhsKtL7xsvw0Z1nHMoJYuQzt4OA',
    appId: '1:584143822337:ios:317696601a896b8d50ea00',
    messagingSenderId: '584143822337',
    projectId: 'mychatapp-e72a0',
    storageBucket: 'mychatapp-e72a0.firebasestorage.app',
    iosBundleId: 'com.example.chatBotDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo9pe7VhsKtL7xsvw0Z1nHMoJYuQzt4OA',
    appId: '1:584143822337:ios:317696601a896b8d50ea00',
    messagingSenderId: '584143822337',
    projectId: 'mychatapp-e72a0',
    storageBucket: 'mychatapp-e72a0.firebasestorage.app',
    iosBundleId: 'com.example.chatBotDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfhHr9cEoqQvLeQr9GTCEThr-79cGlKEU',
    appId: '1:584143822337:web:faf32f492f99f1af50ea00',
    messagingSenderId: '584143822337',
    projectId: 'mychatapp-e72a0',
    authDomain: 'mychatapp-e72a0.firebaseapp.com',
    storageBucket: 'mychatapp-e72a0.firebasestorage.app',
    measurementId: 'G-ZX30H4WMQ7',
  );

}